# Workflow to build and test the project with Gradle
#
# author: Manuel Eberle
# date: 09.09.2022
#

name: Pipeline Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build and Test (full) with Gradle
        run: ./gradlew fullTest

      - name: Build and Test (fast) with Gradle
        run: ./gradlew fastTest

      - name: Publish JUnit Test Results
        uses: EnricoMi/publish-unit-test-result-action/composite@v2
        if: always()
        with:
          junit_files: "build/test-results/**/*.xml"